version: '3.8'

services:
  chat-analyzer:
    image: vikrant82/chat-analyzer:latest
    container_name: chat_analyzer_app
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json:ro
      - sessions_data:/app/sessions
      - cache_data:/app/cache
    restart: unless-stopped

volumes:
  sessions_data:
  cache_data: